### ISSUE TITLE
Implement software-controlled reset

### ISSUE THREAD

**Issue by michaellass** [pc2/Aurora-HLS#10]
Currently the FPGA needs to be reset/reprogrammed to flush the FIFOs in this design. It would be nice to have a software-triggerable reset that purges the FIFOs. This could also then automatically be performed when instantiating the `Aurora` object. 

Before implementing this, one has to think about a proper sequence though, such that purged RX FIFOs are not immediately filled again by outstanding transfers of the connected party (e.g., if flow control was triggered such that not only RX but also TX FIFOs still contain data).

**Comment by papeg** [comment]
I have found no direct way of "flushing" a FIFO in the docs. I think this could be implemented by a component, which is an adapter between 2 axis streams, which just reads values into nothing, when the reset is requested. On the TX-Side this should also happen after the datawidth converter, to prevent something could get stuck in there.

The problem you are mentioning, could it be solved by just waiting for enough time, to catch these? I think its reasonable to assume, that the reset is triggered on all used cores, which are connected. More sophisticated schemes are also possible to imagine, but this may need the use of User-Flow-Control Messages: https://docs.amd.com/r/en-US/pg074-aurora-64b66b/User-Flow-Control-Interface

**Comment by michaellass** [comment]
The FIFOs have a reset signal (`s_axis_aresetn`) which when asserted should drop all data. The data width converters also have a `aresetn` reset input.

The cleanest way to implement this would probably be to reset the entire aurora_hls core and all connected components by triggering its `ap_rst_n` input. Basically:
1. Put aurora_hls into reset
2. Synchronize between all parties (e.g., `MPI_Barrier`)
3. Take aurora_hls out of reset

This will cause some latency as the `aurora_hls_reset` module keeps things in reset for an additional second and the Aurora cores will have to re-establish their links. But it would make sure that we don't miss any buffers and everything is in a clean state.

**Comment by papeg** [comment]
It is planned, that XRT can reset a specific kernel using the regular procedure, which would be the easiest way to solve this:

https://support.xilinx.com/s/question/0D54U00006H9qwCSAR/how-to-reset-the-rtlhls-kernel-at-runtime-after-xclbin-is-programmed?language=en_US

Until then, the only way would be to write a register, but for this the AXI state machine needs to be extended to also support writes:

https://github.com/pc2/Aurora-HLS/blob/0a2d6a40731512dcf8ee66c2a14baaf9ac1d361c/rtl/aurora_hls_control_s_axi.v#L153

From there a "user_reset" signal could be fed into the reset module, to also trigger the full reset.

**Comment by michaellass** [comment]
That limitation of the current state machine is a very good point.

One thing to also keep in mind: If we want to keep aurora_hls in reset until the host code signals (via control registers) that the reset has been initated everywhere, the reset must not affect the AXI control interface itself. Alternatively, maybe a relatively long (i.e., multiple seconds) lasting global reset that ends on its own would be easiest to implement and still be reliable in practice if the host code synchronizes before initiating the reset.

**Comment by michaellass** [comment]
Implemented in #13. The user of Aurora HLS needs to make sure that any connected cores and any FIFOs between Aurora HLS and the connected cores are reset / drained as well.
