### ISSUE TITLE
Add helper functions to support two cores per MPI rank

### ISSUE THREAD

**Issue by papeg** [pc2/Aurora-HLS#11]
Right now, the Aurora class is handling one aurora core. The check_status_core_global() function is assuming that there is one rank per aurora core. But in typical use cases, there is one rank per FPGA, which in this case means two aurora cores. This should be possible to handle in some way, maybe by adapting the Aurora Class or creating another Class which handles two aurora cores.

**Comment by Mellich** [comment]
So what about this issue? Should we declare it as wont-fix? I think the workaround mentioned in #14 is sufficient or are there any objections?

**Comment by papeg** [comment]
Yes, as the ranks are not anymore a part of the helper class, this issue can be closed
