### ISSUE TITLE
Add more general Aurora Constructor

### ISSUE THREAD

**Issue by Mellich** [pc2/Aurora-HLS#18]
Currently, the kernel name for the Aurora cores is hard-coded in the host header files. In most situations, the user will create his/her own bitstream using a custom link configuration. In these cases, the kernel name for the Aurora cores may be arbitrarily chosen by the user. There should be a constructor in our host side interface for the aurora core, that supports arbitrary kernel names.

Suggestion:
Offer a constructor taking a `xrt::kernel` instance.

**Comment by papeg** [comment]
Maybe also another additional constructor taken the name of the kernel as a string would be useful too.

**Comment by Mellich** [comment]
Added in #21
