### ISSUE TITLE
Feature request: Possibility to disable rx or tx ports

### ISSUE THREAD

**Issue by michaellass** [pc2/Aurora-HLS#27]
Feature request by @bwintermann: In simple streaming applications, data typically only flows into one direction. However, currently rx and tx port are always present and have to be connected to other kernels. It would be nice to be able to disable unneeded ports.

**Comment by papeg** [comment]
I think the best way to handle this would be to use the simplex core. But this would need some changes to the internal logic, as the status ports would change:

https://docs.amd.com/r/en-US/pg074-aurora-64b66b/Status-Control-and-Transceiver-Ports

And also the reset sequence seems to be different then:

https://docs.amd.com/r/en-US/pg074-aurora-64b66b/Aurora-64B/66B-Simplex

**Comment by papeg** [comment]
If two cores are used on one device, its also an Option to connect the open RX port with the open TX port of the other core. But not sure if this has side effects. On routing for sure

**Comment by michaellass** [comment]
I'll close this for now as to me it seems simpler to connect some dummy kernels than maintaining additional config options in here.
